#!/usr/bin/env bash
# GitHub Actions runs shell: bash steps under "bash --noprofile --norc -eo pipefail";
# replicate that here since a nested "bash script.sh" invocation does not inherit it.
set -eo pipefail
# SonarQube fails the analysis on a sarifReportPaths entry it cannot read,
# so checkov-sarif.sarif must exist even when checkov is off or finds nothing.
echo '{"version":"2.1.0","$schema":"https://json.schemastore.org/sarif-2.1.0.json","runs":[]}' > checkov-sarif.sarif
echo '{"results":{"failed_checks":[]}}' > checkov-report.json

if [[ "$ENABLE_CHECKOV" != "true" ]]; then
  echo "checkov disabled, skipping"
  exit 0
fi

# --output-file-path entries map 1:1 to the -o flags, in order. They must be
# distinct paths that do not already exist as directories, otherwise checkov
# writes results_<format>.<ext> inside them instead.
# --soft-fail: findings are gated in the summary step, not here.
# --skip-check: these github_actions checks are muted org-wide because their
# detection heuristic can't tell a real finding from the standard safe idiom,
# so they fire on the majority of legitimate workflows:
#   CKV_K8S_11 CPU limits are a bottleneck
#   CKV_GHA_3 flags any run line containing the raw substrings "curl" and
#     "secret" (e.g. `curl -H "Authorization: Bearer $MY_SECRET"` sourced from
#     an env: mapped secret, the recommended-safe pattern). Real interpolation
#     risk is already covered precisely by CKV_GHA_2 (shell injection), kept on.
#   CKV_GHA_5 / CKV_GHA_6 flag any docker/build step lacking a later
#     `cosign sign` / `cosign ... sbom` string in the same job, even when the
#     image is never pushed (PR-only build) or is signed via another job,
#     workflow, or GH-native attestation (actions/attest-build-provenance).
#   CKV_GHA_7 flags any workflow_dispatch with inputs, which is the standard,
#     intentional way to parameterize a manual run (e.g. environment picker);
#     see bridgecrewio/checkov#3839.
#   CKV_DOCKER_2 flags when a dockerfile has no HEALTHCHECK, since we use
#     k8s, there is no requirement for that.
# Extend via checkov_opts; --skip-check is cumulative (argparse action=append),
# so a caller-supplied --skip-check adds to this list instead of replacing it.
# --skip-path: populated from checkov-skip-paths.txt, generated by the
# "Normalize ignore files" step out of .semgrepignore/sonar-project.properties/
# .checkov.yaml, whichever exists, so one exclusion list suppresses opengrep,
# SonarQube and checkov alike.
# Also action=append, so checkov_opts can add further --skip-path entries.
skip_path_args=()
if [[ -s checkov-skip-paths.txt ]]; then
  while IFS= read -r pattern; do
    [[ -n "$pattern" ]] && skip_path_args+=(--skip-path "$pattern")
  done < checkov-skip-paths.txt
fi
checkov -d . \
  --quiet --compact --soft-fail --skip-download \
  --skip-check CKV_GHA_3,CKV_GHA_5,CKV_GHA_6,CKV_GHA_7,CKV_DOCKER_2,CKV_K8S_11,CKV_OPENAPI* \
  "${skip_path_args[@]}" \
  -o cli -o sarif -o json \
  --output-file-path console,checkov-sarif.sarif,checkov-report.json \
  $CHECKOV_OPTS
exit 0
